#!/bin/bash

#SCRIPTFILE=/usr/local/lib/script-after-mount.sh
#SERVICEFILE=/etc/systemd/system/exec-script-after-mount.service
SCRIPTFILE=~/Dokumente/tmp/ttt.test
SERVICEFILE=~/Dokumente/tmp/ttt2.test

echo "There is a timlog at /var/log/execute-script-after-mount-time.log"
read -p "Insert your drive. If it is inserted press enter."
MOUNTUNITS=( $(systemctl list-units -t mount | grep -o ".*\.mount") )

PS3="Please enter your MOUNTUNIT: "
select MOUNTUNIT in ${MOUNTUNITS[@]}
do 
	echo "You selected ${MOUNTUNIT}"
break
done


cat > $SERVICEFILE << ENDOFFILE
[Unit]
Description=Service to execute script after mount of a specific drive
Requires=$MOUNTUNIT
After=$MOUNTUNIT

[Service]
ExecStart=bash "$SCRIPTFILE"

[Install]
WantedBy=$MOUNTUNIT
ENDOFFILE

cat > $SCRIPTFILE << ENDOFFILE
#!/bin/bash
rsync -Icr  "$(zenity --file-selection)" "$PATHTODRIVE"
echo \$(date) >> /var/log/execute-script-after-mount-time.log
ENDOFFILE
